#!/bin/sh

t=0
for f in $(find . -type f | grep -v '/\.'); do
    grep '!!$' "$f" >/dev/null
    if [ $? -eq 0 ]; then
        echo "!! found in $f"
        grep '!!$' "$f"
        t=1
    fi
done

exit $t
